### ISSUE TITLE
请教个关于iOS9适配的问题

### ISSUE THREAD

**Issue by SatanWoo** [ChenYilong/iOS9AdaptationTips#1]
按照文章中的适配，比如添加了微信的Scheme weixin，可以成功唤起微信一次，但是分享完回调之后再次尝试分享到微信，就显示没有安装微信了，请问您有遇到过吗？

**Comment by ChenYilong** [comment]
之所以显示没有安装微信，是因为你调用了：

    [[UIApplication sharedApplication]
                        canOpenURL:[NSURL URLWithString:@"weixin://"]];

如果你确实安装了微信，这个方法在iOS8及其之前的版本会返回YES，但是在iOS9上可能会返回NO，

如果微信客户端还未进行iOS9适配的话，

微信方同样也需要在info.plist中写入一行代码


    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>weixin</string>
    </array>

暂时只能等待微信更新。
