### ISSUE TITLE
可以补充的一个地方。

### ISSUE THREAD

**Issue by tounaobun** [ChenYilong/iOS9AdaptationTips#20]
关于第二条（2.Demo2_iOS9新特性_更灵活的后台定位）除了往Info.plist手动添加key/value外，还可以从Capabilities->Background Modes->开启Location Updates。

**Comment by tounaobun** [comment]
abc
![Uploading Screen Shot 2015-09-29 at 10.20.21 AM.png…]()

![Uploading Screen Shot 2015-09-29 at 10.20.21 AM.png…]()

**Comment by ChenYilong** [comment]
谢谢您的提醒，您看这样 [修改](https://github.com/ChenYilong/iOS9AdaptationTips#2demo2_ios9新特性_更灵活的后台定位) 可以不？
