### ISSUE TITLE
通过Category覆盖系统方法并不可取

### ISSUE THREAD

**Issue by tielei** [ChenYilong/iOS9AdaptationTips#24]
文中提到的通过Category重写preferredStatusBarStyle的方式来指定status bar样式，并不可取。按照苹果官方的解释：
If the name of a method declared in a category is the same as a method in the original class, or a method in another category on the same class (or even a superclass), the behavior is undefined as to which method implementation is used at runtime. This is less likely to be an issue if you’re using categories with your own classes, but can cause problems when using categories to add methods to standard Cocoa or Cocoa Touch classes.

**Comment by wyyfeeling** [comment]
issue

**Comment by ChenYilong** [comment]
嗯，对，已经做了 [说明](https://github.com/ChenYilong/iOS9AdaptationTips/commit/da0c28460cb082cbc630804552cde9a365dfd3cb) 。非常感谢提醒，你再看看有什么其他不对的地方。欢迎提。
