### ISSUE TITLE
URLScheme白名单

### ISSUE THREAD

**Issue by wigl** [ChenYilong/iOS9AdaptationTips#29]
有个APP，地址如下：
https://itunes.apple.com/us/app/launcher-notification-center/id905099592?mt=8
它可以检测手机上安装的APP，里面成有千上万的APP列表，URLScheme白名单不可能添加这么多。
那它是怎能可以检测那么多APP呢？

**Comment by ChenYilong** [comment]
推测有三种可能性，第一种可能是使用私有api,第二种是sdk版本基于8.x及更早版本，第三种是直接使用了openURL，然后判断该方法的返回值，进行检测，没有使用canOpen方法。

**Comment by wigl** [comment]
应该没有使用私有API，毕竟苹果禁止，不容易过审核。
另外，前几天把这个APP的ipa文件解压了，发现里面Info.plist文件中有4000多个URLScheme，所以应该用了openURL或者canOpen，那就有了新的问题：
1、如果使用了canOpen，那因为可能因为sdk版本较低，所以在iOS9设备上URLScheme白名单不起作用？
2、如果使用了openURL，那就不用考虑白名单的问题，但是这会导致弹出“xx想打开你的xx应用”的警告视图，它又是如何避免这个弹窗的出现呢？
