### ISSUE TITLE
關於URL Scheme

### ISSUE THREAD

**Issue by powhu** [ChenYilong/iOS9AdaptationTips#3]
> [UPDATE #2: I have independent confirmation from several sources that these limitations are meant to only apply to “canOpenURL” and it is a bug that they are also effecting “openURL”. There are still implications, and many apps will need some updates, but that’s not so dramatic a change.]

參考的[連結](http://awkwardhare.com/post/121196006730/quick-take-on-ios-9-url-scheme-changes)的文章更新了，有提到是bug，麻煩追記一下

**Comment by ChenYilong** [comment]
已经[更新](https://github.com/ChenYilong/iOS9AdaptationTips/commit/cc89a466bf103bcdadfa0b8c0a0f9d0ab21c260a)了，你看下这样描述对不对。
