### ISSUE TITLE
关于HTTPS 和 使用 AFNetWorking

### ISSUE THREAD

**Issue by xxxIxxxx** [ChenYilong/iOS9AdaptationTips#37]
1.  检测 https 是否符合 ATS 使用 `$ nscurl --verbose --ats-diagnostics https://<your_server_domain>`
   输出结果都是pass  是不是就是符合。
2. 我使用的是最新的AFNETWorking 3.0   已经改为了**AFHTTPSessionManager** 并且在info.plist 添加了 `NSAllowsArbitraryLoads = YES`
   但请求 **https** 时依然  报错 `Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server."`
   请问这是为什么啊

**Comment by GarfieldLover** [comment]
你解决了吗，我的也是这样，-1004
