### ISSUE TITLE
后台用的不是定位，而是Background fetch，也是报和定位差不多的错误，该怎么处理呢？

### ISSUE THREAD

**Issue by poholo** [ChenYilong/iOS9AdaptationTips#4]
Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3491.2.5/UIApplication.m:3173
(lldb)

**Comment by ChenYilong** [comment]
刚看到，解决没呢？

**Comment by poholo** [comment]
嗯，解决了，是我这边rootviewcontroller等数据有延时造成的~  感谢

**Comment by BensterS** [comment]
怎么解决的？？？
我也碰到这个问题了
